/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2026-05-27 13:43:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.book;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bookList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1775651435076L));
    _jspx_dependants.put("jar:file:/C:/eGov/workspace-egov/poly-library-v3/poly-library-updated2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/poly-library/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>도서 목록 - 폴리 인공지능 도서관</title>\n");
      out.write("<style>\n");
      out.write("* { margin:0; padding:0; box-sizing:border-box; }\n");
      out.write("body { font-family:'Georgia',serif; background-color:#F5F0E8; color:#3B2F2F; min-height:100vh; }\n");
      out.write(".header { background-color:#5C3D2E; box-shadow:0 2px 8px rgba(0,0,0,0.3); position:relative; z-index:100; }\n");
      out.write(".header-inner { max-width:1100px; margin:0 auto; padding:20px 30px; display:flex; align-items:center; justify-content:space-between; }\n");
      out.write(".header h1 { color:#F5E6C8; font-size:22px; letter-spacing:1px; }\n");
      out.write(".header .subtitle { color:#C4A882; font-size:13px; margin-top:4px; }\n");
      out.write(".nav-links { display:flex; align-items:center; gap:20px; }\n");
      out.write(".nav-links a { color:#F5E6C8; text-decoration:none; font-size:14px; }\n");
      out.write(".nav-links a:hover { color:#E8C87A; }\n");
      out.write("\n");
      out.write("/* 헤더 드롭다운 */\n");
      out.write(".user-menu { position:relative; }\n");
      out.write(".user-btn { color:#C4A882; font-size:13px; font-weight:bold; cursor:pointer; background:none; border:none; font-family:inherit; display:flex; align-items:center; gap:6px; padding:4px 0; }\n");
      out.write(".user-btn:hover { color:#F5E6C8; }\n");
      out.write(".user-btn .arrow { font-size:10px; transition:transform 0.2s; }\n");
      out.write(".user-menu.open .arrow { transform:rotate(180deg); }\n");
      out.write(".dropdown { display:none; position:absolute; top:calc(100% + 14px); right:0; width:280px; background:#FFFDF8; border-radius:10px; box-shadow:0 8px 30px rgba(0,0,0,0.25); border:1px solid #EDE0CE; overflow:hidden; }\n");
      out.write(".user-menu.open .dropdown { display:block; animation:fadeDown 0.18s ease; }\n");
      out.write("@keyframes fadeDown { from{opacity:0;transform:translateY(-8px)} to{opacity:1;transform:translateY(0)} }\n");
      out.write(".dropdown-header { background:#5C3D2E; padding:12px 16px; color:#F5E6C8; font-size:13px; font-weight:bold; }\n");
      out.write(".dropdown-body { padding:10px 0; max-height:260px; overflow-y:auto; }\n");
      out.write(".loan-item { padding:10px 16px; border-bottom:1px solid #F0E8DC; }\n");
      out.write(".loan-item:last-child { border-bottom:none; }\n");
      out.write(".li-title { font-size:13px; font-weight:bold; color:#3B2F2F; margin-bottom:3px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }\n");
      out.write(".li-meta { font-size:11px; color:#A08060; display:flex; justify-content:space-between; align-items:center; }\n");
      out.write(".li-dday { font-size:11px; font-weight:bold; padding:2px 7px; border-radius:10px; }\n");
      out.write(".dday-ok  { background:#E8F5E9; color:#2E7D32; }\n");
      out.write(".dday-warn { background:#FFF3E0; color:#E65100; }\n");
      out.write(".dday-over { background:#FFEBEE; color:#C62828; }\n");
      out.write(".empty-drop { padding:20px 16px; text-align:center; font-size:13px; color:#A08060; }\n");
      out.write(".dropdown-footer { border-top:1px solid #EDE0CE; padding:10px 16px; text-align:center; }\n");
      out.write(".dropdown-footer a { color:#A0522D; text-decoration:none; font-size:13px; font-weight:bold; }\n");
      out.write(".dropdown-footer a:hover { text-decoration:underline; }\n");
      out.write("\n");
      out.write(".container { max-width:1100px; margin:40px auto; padding:0 30px; }\n");
      out.write(".page-header { display:flex; align-items:center; justify-content:space-between; margin-bottom:20px; flex-wrap:wrap; gap:12px; }\n");
      out.write(".page-title { font-size:26px; color:#5C3D2E; font-weight:bold; border-left:5px solid #A0522D; padding-left:14px; }\n");
      out.write(".btn-group { display:flex; gap:10px; align-items:center; }\n");
      out.write(".btn-register { background-color:#A0522D; color:#FFF8F0; padding:10px 22px; border:none; border-radius:6px; font-size:14px; cursor:pointer; text-decoration:none; display:inline-block; }\n");
      out.write(".btn-register:hover { background-color:#7B3A1F; }\n");
      out.write(".btn-loan { background-color:#2E7D6B; color:#FFFFFF; padding:10px 22px; border:none; border-radius:6px; font-size:14px; font-weight:bold; cursor:pointer; display:inline-block; }\n");
      out.write(".btn-loan:hover { background-color:#1E5C4E; }\n");
      out.write(".search-box { background:#FFFDF8; border-radius:10px; box-shadow:0 2px 8px rgba(92,61,46,0.1); padding:16px 20px; margin-bottom:20px; display:flex; gap:10px; align-items:center; flex-wrap:wrap; }\n");
      out.write(".search-box select,.search-box input { padding:9px 14px; border:1.5px solid #D4B896; border-radius:6px; font-size:14px; background:#FFF8F0; font-family:inherit; }\n");
      out.write(".btn-search { background-color:#5C3D2E; color:#FFF8F0; padding:9px 22px; border:none; border-radius:6px; cursor:pointer; font-family:inherit; font-size:14px; }\n");
      out.write(".btn-search:hover { background-color:#3D2719; }\n");
      out.write(".toast { display:none; position:fixed; top:24px; left:50%; transform:translateX(-50%); background:#2E7D6B; color:#fff; padding:12px 28px; border-radius:8px; font-size:14px; font-weight:bold; z-index:9999; box-shadow:0 4px 16px rgba(0,0,0,0.2); }\n");
      out.write(".toast.err { background:#C62828; }\n");
      out.write(".table-card { background:#FFFDF8; border-radius:12px; box-shadow:0 2px 12px rgba(92,61,46,0.1); overflow:hidden; }\n");
      out.write("table { width:100%; border-collapse:collapse; }\n");
      out.write("thead tr { background-color:#5C3D2E; }\n");
      out.write("thead th { color:#F5E6C8; padding:16px 12px; font-size:14px; text-align:center; }\n");
      out.write("tbody td { padding:14px 12px; font-size:14px; text-align:center; color:#4A3728; border-bottom:1px solid #EDE0CE; }\n");
      out.write("tbody tr:hover { background-color:#FFF8EE; }\n");
      out.write(".badge { display:inline-block; padding:4px 10px; border-radius:20px; font-size:12px; font-weight:bold; }\n");
      out.write(".badge-available { background-color:#E8F5E9; color:#2E7D32; }\n");
      out.write(".badge-loaned { background-color:#FFF3E0; color:#E65100; }\n");
      out.write(".btn-edit { background:#E8D5B0; color:#5C3D2E; padding:6px 14px; border-radius:4px; font-size:12px; text-decoration:none; margin-right:4px; }\n");
      out.write(".btn-delete { background:#F5D5CC; color:#7B2D2D; padding:6px 14px; border-radius:4px; font-size:12px; text-decoration:none; }\n");
      out.write(".empty-msg { text-align:center; padding:40px; color:#A08060; font-size:15px; }\n");
      out.write(".footer { text-align:center; margin-top:60px; padding:24px; color:#A08060; font-size:13px; border-top:1px solid #DDD0BC; }\n");
      out.write("\n");
      out.write("/* 대출 모달 */\n");
      out.write(".modal-overlay { display:none; position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.55); z-index:1000; justify-content:center; align-items:center; }\n");
      out.write(".modal-overlay.active { display:flex; }\n");
      out.write(".modal { background:#FFFDF8; border-radius:14px; box-shadow:0 8px 40px rgba(0,0,0,0.3); width:100%; max-width:700px; max-height:90vh; overflow-y:auto; padding:32px 32px 24px; position:relative; animation:slideUp 0.22s ease; }\n");
      out.write("@keyframes slideUp { from{transform:translateY(30px);opacity:0;} to{transform:translateY(0);opacity:1;} }\n");
      out.write(".modal-close { position:absolute; top:16px; right:20px; background:none; border:none; font-size:24px; cursor:pointer; color:#A08060; }\n");
      out.write(".modal-close:hover { color:#5C3D2E; }\n");
      out.write(".modal h2 { color:#5C3D2E; font-size:20px; margin-bottom:4px; }\n");
      out.write(".modal-subtitle { color:#A08060; font-size:13px; margin-bottom:18px; }\n");
      out.write(".modal-divider { border:none; border-top:1px solid #EDE0CE; margin:16px 0; }\n");
      out.write(".sec-title { font-size:13px; font-weight:bold; color:#5C3D2E; margin-bottom:8px; }\n");
      out.write("\n");
      out.write("/* 검색 */\n");
      out.write(".modal-search-row { display:flex; gap:8px; margin-bottom:10px; }\n");
      out.write(".modal-search-row select { padding:9px 12px; border:1.5px solid #D4B896; border-radius:6px; background:#FFF8F0; font-family:inherit; font-size:13px; }\n");
      out.write(".modal-search-row input { flex:1; padding:9px 14px; border:1.5px solid #D4B896; border-radius:6px; background:#FFF8F0; font-family:inherit; font-size:13px; }\n");
      out.write(".modal-search-row input:focus,.modal-search-row select:focus { outline:none; border-color:#A0522D; }\n");
      out.write(".btn-ms { background:#5C3D2E; color:#FFF8F0; border:none; border-radius:6px; padding:9px 18px; cursor:pointer; font-size:13px; white-space:nowrap; font-family:inherit; }\n");
      out.write(".btn-ms:hover { background:#3D2719; }\n");
      out.write("\n");
      out.write("/* 검색 결과 */\n");
      out.write(".result-box { background:#F9F4EE; border:1.5px solid #EDE0CE; border-radius:8px; min-height:68px; padding:10px 12px; font-size:13px; color:#A08060; display:flex; flex-direction:column; gap:5px; }\n");
      out.write(".result-item { background:#FFFDF8; border:1px solid #D4B896; border-radius:6px; padding:9px 12px; cursor:pointer; width:100%; font-size:13px; color:#3B2F2F; display:flex; align-items:center; gap:10px; transition:background 0.12s,border-color 0.12s; }\n");
      out.write(".result-item:hover { background:#FFF0DC; border-color:#A0522D; }\n");
      out.write(".result-item.selected { background:#FFF0DC; border-color:#2E7D6B; }\n");
      out.write(".result-item.disabled { opacity:0.5; cursor:not-allowed; }\n");
      out.write(".ri-check { width:22px; height:22px; border-radius:50%; border:2px solid #D4B896; display:flex; align-items:center; justify-content:center; flex-shrink:0; font-size:12px; transition:all 0.15s; }\n");
      out.write(".result-item.selected .ri-check { background:#2E7D6B; border-color:#2E7D6B; color:white; }\n");
      out.write(".ri-info { flex:1; }\n");
      out.write(".item-title { font-weight:bold; color:#5C3D2E; margin-bottom:2px; }\n");
      out.write(".item-sub { font-size:12px; color:#A08060; }\n");
      out.write(".rbadge { display:inline-block; padding:2px 8px; border-radius:12px; font-size:11px; margin-left:6px; }\n");
      out.write(".rb-ok { background:#E8F5E9; color:#2E7D32; }\n");
      out.write(".rb-no { background:#FFF3E0; color:#E65100; }\n");
      out.write(".hint { font-size:12px; color:#B09070; margin-top:4px; }\n");
      out.write("\n");
      out.write("/* 선택된 도서 바구니 */\n");
      out.write(".cart-area { background:#F0FFF8; border:1.5px solid #A8D5C8; border-radius:8px; padding:12px 14px; margin-top:14px; }\n");
      out.write(".cart-title { font-size:12px; font-weight:bold; color:#2E7D6B; margin-bottom:8px; display:flex; justify-content:space-between; align-items:center; }\n");
      out.write(".cart-title span { font-weight:normal; font-size:11px; color:#A08060; cursor:pointer; text-decoration:underline; }\n");
      out.write(".cart-item { display:flex; align-items:center; justify-content:space-between; background:#FFFDF8; border:1px solid #C8E6DC; border-radius:6px; padding:7px 10px; margin-bottom:5px; font-size:12px; }\n");
      out.write(".cart-item:last-child { margin-bottom:0; }\n");
      out.write(".cart-item-title { font-weight:bold; color:#3B2F2F; }\n");
      out.write(".cart-item-sub { color:#A08060; font-size:11px; margin-top:1px; }\n");
      out.write(".cart-remove { background:none; border:none; color:#A08060; cursor:pointer; font-size:14px; padding:0 4px; line-height:1; }\n");
      out.write(".cart-remove:hover { color:#C62828; }\n");
      out.write(".cart-return-date { font-size:11px; color:#2E7D6B; margin-top:2px; }\n");
      out.write("\n");
      out.write("/* 대출 신청 버튼 */\n");
      out.write(".btn-submit-loan { width:100%; background:#2E7D6B; color:white; border:none; border-radius:8px; padding:13px; font-size:15px; font-weight:bold; cursor:pointer; margin-top:14px; font-family:inherit; transition:background 0.2s; }\n");
      out.write(".btn-submit-loan:hover { background:#1E5C4E; }\n");
      out.write(".btn-submit-loan:disabled { background:#A8BFBA; cursor:not-allowed; }\n");
      out.write("\n");
      out.write("/* 비로그인 */\n");
      out.write(".login-required-box { background:#FFF8EE; border:1.5px solid #E8C87A; border-radius:10px; padding:20px; text-align:center; }\n");
      out.write(".lrb-title { font-size:15px; font-weight:bold; color:#5C3D2E; margin-bottom:8px; }\n");
      out.write(".lrb-sub { font-size:13px; color:#A08060; margin-bottom:18px; }\n");
      out.write(".lrb-btn-row { display:flex; gap:10px; justify-content:center; }\n");
      out.write(".btn-go-login { background:#5C3D2E; color:#FFF8F0; border:none; border-radius:6px; padding:11px 28px; font-size:14px; font-weight:bold; cursor:pointer; font-family:inherit; text-decoration:none; display:inline-block; }\n");
      out.write(".btn-go-login:hover { background:#3D2719; }\n");
      out.write(".btn-go-join { background:#FFFDF8; color:#5C3D2E; border:1.5px solid #A0522D; border-radius:6px; padding:11px 28px; font-size:14px; cursor:pointer; font-family:inherit; text-decoration:none; display:inline-block; }\n");
      out.write(".btn-go-join:hover { background:#FFF0DC; }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div id=\"toast\" class=\"toast\"></div>\n");
      out.write("\n");
      out.write("<div class=\"header\">\n");
      out.write("  <div class=\"header-inner\">\n");
      out.write("    <div>\n");
      out.write("      <h1>📚 폴리 인공지능 도서관</h1>\n");
      out.write("      <div class=\"subtitle\">Poly AI Library Management System</div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"nav-links\">\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/book/bookList.do\">도서 목록</a>\n");
      out.write("      ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("  <div class=\"page-header\">\n");
      out.write("    <div class=\"page-title\">도서 목록</div>\n");
      out.write("    <div class=\"btn-group\">\n");
      out.write("      <button class=\"btn-loan\" onclick=\"openLoanModal()\">📖 도서 대여</button>\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"search-box\">\n");
      out.write("    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/book/bookSearch.do\" method=\"get\" style=\"display:flex;gap:10px;align-items:center;flex-wrap:wrap;width:100%;\">\n");
      out.write("      <select name=\"searchType\">\n");
      out.write("        <option value=\"title\" ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(">제목</option>\n");
      out.write("        <option value=\"author\" ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write(">저자</option>\n");
      out.write("        <option value=\"publisher\" ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write(">출판사</option>\n");
      out.write("      </select>\n");
      out.write("      <input type=\"text\" name=\"keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"검색어를 입력하세요\" style=\"flex:1;min-width:180px;\">\n");
      out.write("      <button type=\"submit\" class=\"btn-search\">검색</button>\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"table-card\">\n");
      out.write("    <table>\n");
      out.write("      <thead>\n");
      out.write("        <tr>\n");
      out.write("          <th>번호</th>\n");
      out.write("          <th>도서명</th>\n");
      out.write("          <th>저자</th>\n");
      out.write("          <th>출판사</th>\n");
      out.write("          <th>상태</th>\n");
      out.write("          ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </tr>\n");
      out.write("      </thead>\n");
      out.write("      <tbody>\n");
      out.write("        ");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("      </tbody>\n");
      out.write("    </table>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"footer\">2026 폴리 인공지능 도서관 - Poly AI Library</div>\n");
      out.write("\n");
      out.write("<div class=\"modal-overlay\" id=\"loanModal\" onclick=\"closeBg(event)\">\n");
      out.write("  <div class=\"modal\">\n");
      out.write("    <button class=\"modal-close\" onclick=\"closeLoanModal()\">✕</button>\n");
      out.write("    <h2>📖 도서 대출 신청</h2>\n");
      out.write("    ");
      if (_jspx_meth_c_005fchoose_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("var CP = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("var dropLoaded = false;\n");
      out.write("\n");
      out.write("/* ── 장바구니: bookId → book 객체 ── */\n");
      out.write("var cart = {};\n");
      out.write("\n");
      out.write("/* ── 토스트 ── */\n");
      out.write("function showToast(msg, isErr) {\n");
      out.write("  var t = document.getElementById('toast');\n");
      out.write("  t.textContent = msg;\n");
      out.write("  t.className = 'toast' + (isErr ? ' err' : '');\n");
      out.write("  t.style.display = 'block';\n");
      out.write("  setTimeout(function(){ t.style.display = 'none'; }, 3000);\n");
      out.write("}\n");
      out.write("(function(){\n");
      out.write("  var p = new URLSearchParams(window.location.search);\n");
      out.write("  var m = p.get('msg');\n");
      out.write("  if(m) showToast(decodeURIComponent(m), m.indexOf('오류') > -1 || m.indexOf('이미') > -1);\n");
      out.write("})();\n");
      out.write("\n");
      out.write("/* ── 헤더 드롭다운 ── */\n");
      out.write("function toggleDropdown() {\n");
      out.write("  var menu = document.getElementById('userMenu');\n");
      out.write("  var isOpen = menu.classList.contains('open');\n");
      out.write("  if(isOpen) { menu.classList.remove('open'); }\n");
      out.write("  else { menu.classList.add('open'); if(!dropLoaded) loadLoanSummary(); }\n");
      out.write("}\n");
      out.write("document.addEventListener('click', function(e) {\n");
      out.write("  var menu = document.getElementById('userMenu');\n");
      out.write("  if(menu && !menu.contains(e.target)) menu.classList.remove('open');\n");
      out.write("});\n");
      out.write("function loadLoanSummary() {\n");
      out.write("  ajax(CP + '/loan/myLoanSummary.do', function(data) {\n");
      out.write("    dropLoaded = true;\n");
      out.write("    var body = document.getElementById('dropdownBody');\n");
      out.write("    if(!data || !data.length) { body.innerHTML = '<div class=\"empty-drop\">대출 중인 도서가 없습니다.</div>'; return; }\n");
      out.write("    var h = '';\n");
      out.write("    data.forEach(function(loan) {\n");
      out.write("      var dc = loan.ddayClass || 'dday-ok';\n");
      out.write("      h += '<div class=\"loan-item\">';\n");
      out.write("      h += '<div class=\"li-title\">' + safeText(loan.bookTitle) + '</div>';\n");
      out.write("      h += '<div class=\"li-meta\"><span>반납예정: ' + safeText(loan.returnDate) + '</span>';\n");
      out.write("      h += '<span class=\"li-dday ' + dc + '\">' + safeText(loan.ddayLabel) + '</span></div>';\n");
      out.write("      h += '</div>';\n");
      out.write("    });\n");
      out.write("    body.innerHTML = h;\n");
      out.write("  }, function() {\n");
      out.write("    document.getElementById('dropdownBody').innerHTML = '<div class=\"empty-drop\">불러오기 실패</div>';\n");
      out.write("  });\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 모달 open/close ── */\n");
      out.write("function openLoanModal() { document.getElementById('loanModal').classList.add('active'); document.body.style.overflow = 'hidden'; }\n");
      out.write("function closeLoanModal() { document.getElementById('loanModal').classList.remove('active'); document.body.style.overflow = ''; }\n");
      out.write("function closeBg(e) { if(e.target === document.getElementById('loanModal')) closeLoanModal(); }\n");
      out.write("\n");
      out.write("/* ── 14일 후 날짜 ── */\n");
      out.write("function calcReturnDate() {\n");
      out.write("  var d = new Date();\n");
      out.write("  d.setDate(d.getDate() + 14);\n");
      out.write("  return d.getFullYear() + '-' + pad(d.getMonth()+1) + '-' + pad(d.getDate());\n");
      out.write("}\n");
      out.write("function pad(n){ return String(n).padStart(2,'0'); }\n");
      out.write("\n");
      out.write("/* ── 도서 검색 ── */\n");
      out.write("var searchCache = {};\n");
      out.write("function searchBook() {\n");
      out.write("  var t = document.getElementById('bookSearchType').value;\n");
      out.write("  var k = document.getElementById('bookKeyword').value.trim();\n");
      out.write("  var box = document.getElementById('bookResultBox');\n");
      out.write("  if(!k) { box.innerHTML = '<span>검색어를 입력해주세요.</span>'; return; }\n");
      out.write("  box.innerHTML = '<span>검색 중...</span>';\n");
      out.write("  ajax(CP + '/loan/searchBook.do?searchType=' + enc(t) + '&keyword=' + enc(k), function(data) {\n");
      out.write("    /* 검색 결과를 캐시에도 저장 */\n");
      out.write("    if(data) data.forEach(function(b){ searchCache[b.bookId] = b; });\n");
      out.write("    renderResults(data);\n");
      out.write("  }, function() {\n");
      out.write("    box.innerHTML = '<span style=\"color:#C0392B;\">서버 오류가 발생했습니다.</span>';\n");
      out.write("  });\n");
      out.write("}\n");
      out.write("\n");
      out.write("function renderResults(data) {\n");
      out.write("  var box = document.getElementById('bookResultBox');\n");
      out.write("  if(!data || !data.length) { box.innerHTML = '<span>검색 결과가 없습니다.</span>'; return; }\n");
      out.write("  var h = '';\n");
      out.write("  data.forEach(function(b) {\n");
      out.write("    var av = b.status === 'Y';\n");
      out.write("    var inCart = !!cart[b.bookId];\n");
      out.write("    var cls = 'result-item' + (!av ? ' disabled' : (inCart ? ' selected' : ''));\n");
      out.write("    h += '<div class=\"' + cls + '\" data-bookid=\"' + b.bookId + '\">';\n");
      out.write("    h += '<div class=\"ri-check\">' + (inCart ? '✔' : '') + '</div>';\n");
      out.write("    h += '<div class=\"ri-info\">';\n");
      out.write("    h += '<div class=\"item-title\">' + safeText(b.title);\n");
      out.write("    h += av ? '<span class=\"rbadge rb-ok\">대출가능</span>' : '<span class=\"rbadge rb-no\">대출중</span>';\n");
      out.write("    h += '</div>';\n");
      out.write("    h += '<div class=\"item-sub\">저자: ' + safeText(b.author) + ' | 출판사: ' + safeText(b.publisher) + '</div>';\n");
      out.write("    h += '</div></div>';\n");
      out.write("  });\n");
      out.write("  box.innerHTML = h;\n");
      out.write("\n");
      out.write("  /* 클릭 이벤트 — data-bookid 방식으로 JSON.stringify 문제 완전 우회 */\n");
      out.write("  box.querySelectorAll('.result-item').forEach(function(el) {\n");
      out.write("    el.addEventListener('click', function() {\n");
      out.write("      var bid = parseInt(el.getAttribute('data-bookid'));\n");
      out.write("      var book = searchCache[bid];\n");
      out.write("      if(!book || book.status !== 'Y') { showToast('대출 중인 도서입니다.', true); return; }\n");
      out.write("      if(cart[bid]) {\n");
      out.write("        delete cart[bid];\n");
      out.write("        el.classList.remove('selected');\n");
      out.write("        el.querySelector('.ri-check').textContent = '';\n");
      out.write("      } else {\n");
      out.write("        cart[bid] = book;\n");
      out.write("        el.classList.add('selected');\n");
      out.write("        el.querySelector('.ri-check').textContent = '✔';\n");
      out.write("      }\n");
      out.write("      updateCart();\n");
      out.write("    });\n");
      out.write("  });\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 장바구니 UI 업데이트 ── */\n");
      out.write("function updateCart() {\n");
      out.write("  var keys = Object.keys(cart);\n");
      out.write("  var cartArea = document.getElementById('cartArea');\n");
      out.write("  var cartList = document.getElementById('cartList');\n");
      out.write("  var cartCount = document.getElementById('cartCount');\n");
      out.write("  var btnCount = document.getElementById('btnCount');\n");
      out.write("  var btn = document.getElementById('loanSubmitBtn');\n");
      out.write("  var hiddens = document.getElementById('cartHiddens');\n");
      out.write("\n");
      out.write("  cartCount.textContent = keys.length;\n");
      out.write("  btnCount.textContent = keys.length;\n");
      out.write("  btn.disabled = keys.length === 0;\n");
      out.write("\n");
      out.write("  if(keys.length === 0) {\n");
      out.write("    cartArea.style.display = 'none';\n");
      out.write("    cartList.innerHTML = '';\n");
      out.write("    hiddens.innerHTML = '';\n");
      out.write("    return;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  cartArea.style.display = 'block';\n");
      out.write("  var h = '';\n");
      out.write("  var hh = '';\n");
      out.write("  var rd = calcReturnDate();\n");
      out.write("  keys.forEach(function(bid) {\n");
      out.write("    var b = cart[bid];\n");
      out.write("    h += '<div class=\"cart-item\">';\n");
      out.write("    h += '<div><div class=\"cart-item-title\">' + safeText(b.title) + '</div>';\n");
      out.write("    h += '<div class=\"cart-item-sub\">저자: ' + safeText(b.author) + '</div>';\n");
      out.write("    h += '<div class=\"cart-return-date\">반납예정: ' + rd + '</div></div>';\n");
      out.write("    h += '<button class=\"cart-remove\" data-remove=\"' + bid + '\">✕</button>';\n");
      out.write("    h += '</div>';\n");
      out.write("    hh += '<input type=\"hidden\" name=\"bookIds\" value=\"' + bid + '\">';\n");
      out.write("  });\n");
      out.write("  cartList.innerHTML = h;\n");
      out.write("  hiddens.innerHTML = hh;\n");
      out.write("\n");
      out.write("  /* 장바구니 제거 버튼 */\n");
      out.write("  cartList.querySelectorAll('.cart-remove').forEach(function(btn) {\n");
      out.write("    btn.addEventListener('click', function() {\n");
      out.write("      var bid = parseInt(btn.getAttribute('data-remove'));\n");
      out.write("      delete cart[bid];\n");
      out.write("      /* 현재 검색 결과에서도 선택 해제 */\n");
      out.write("      var el = document.querySelector('.result-item[data-bookid=\"' + bid + '\"]');\n");
      out.write("      if(el) { el.classList.remove('selected'); el.querySelector('.ri-check').textContent = ''; }\n");
      out.write("      updateCart();\n");
      out.write("    });\n");
      out.write("  });\n");
      out.write("}\n");
      out.write("\n");
      out.write("function clearCart() {\n");
      out.write("  cart = {};\n");
      out.write("  document.querySelectorAll('.result-item.selected').forEach(function(el) {\n");
      out.write("    el.classList.remove('selected');\n");
      out.write("    el.querySelector('.ri-check').textContent = '';\n");
      out.write("  });\n");
      out.write("  updateCart();\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 대출 신청 ── */\n");
      out.write("function submitLoan() {\n");
      out.write("  var keys = Object.keys(cart);\n");
      out.write("  if(keys.length === 0) { alert('도서를 선택해주세요.'); return; }\n");
      out.write("  var titles = keys.map(function(k){ return '\"' + cart[k].title + '\"'; }).join(', ');\n");
      out.write("  if(confirm(keys.length + '권을 대출하시겠습니까?\\n' + titles + '\\n\\n반납예정일: ' + calcReturnDate()))\n");
      out.write("    document.getElementById('loanForm').submit();\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 유틸 ── */\n");
      out.write("function safeText(s) {\n");
      out.write("  if(!s) return '';\n");
      out.write("  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');\n");
      out.write("}\n");
      out.write("function ajax(url, success, error) {\n");
      out.write("  var x = new XMLHttpRequest();\n");
      out.write("  x.open('GET', url, true);\n");
      out.write("  x.onload = function() {\n");
      out.write("    if(x.status === 200) { try { success(JSON.parse(x.responseText)); } catch(e) { error && error(e); } }\n");
      out.write("    else { error && error(); }\n");
      out.write("  };\n");
      out.write("  x.onerror = function() { error && error(); };\n");
      out.write("  x.send();\n");
      out.write("}\n");
      out.write("function enc(s) { return encodeURIComponent(s); }\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("        ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/jsp/book/bookList.jsp(148,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginVO}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("          <div class=\"user-menu\" id=\"userMenu\">\n");
          out.write("            <button class=\"user-btn\" onclick=\"toggleDropdown()\">\n");
          out.write("              ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVO.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 <span class=\"arrow\">▼</span>\n");
          out.write("            </button>\n");
          out.write("            <div class=\"dropdown\" id=\"dropdown\">\n");
          out.write("              <div class=\"dropdown-header\">📋 내 대출 현황</div>\n");
          out.write("              <div class=\"dropdown-body\" id=\"dropdownBody\">\n");
          out.write("                <div class=\"empty-drop\">불러오는 중...</div>\n");
          out.write("              </div>\n");
          out.write("              <div class=\"dropdown-footer\">\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/loan/myLoan.do\">전체 보기 →</a>\n");
          out.write("              </div>\n");
          out.write("            </div>\n");
          out.write("          </div>\n");
          out.write("          <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/user/logout.do\" onclick=\"return confirm('로그아웃 하시겠습니까?')\">로그아웃</a>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("          <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/user/loginView.do\">로그인</a>\n");
          out.write("          <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/user/joinView.do\">회원가입</a>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/book/bookList.jsp(179,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVO.role == 'ADMIN'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/book/bookRegisterView.do\" class=\"btn-register\">+ 도서 등록</a>\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/jsp/book/bookList.jsp(188,30) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchType=='title'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/jsp/book/bookList.jsp(189,31) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchType=='author'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/jsp/book/bookList.jsp(190,34) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchType=='publisher'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/jsp/book/bookList.jsp(194,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty keyword}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/book/bookList.do\" class=\"btn-search\" style=\"text-decoration:none;background:#A08060;\">전체 보기</a>\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/jsp/book/bookList.jsp(209,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVO.role == 'ADMIN'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<th>관리</th>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("          ");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("          ");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/jsp/book/bookList.jsp(214,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty bookList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            <tr><td colspan=\"6\" class=\"empty-msg\">등록된 도서가 없습니다.</td></tr>\n");
          out.write("          ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            ");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fotherwise_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("          ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f1);
      // /WEB-INF/jsp/book/bookList.jsp(218,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("book");
      // /WEB-INF/jsp/book/bookList.jsp(218,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/book/bookList.jsp(218,12) '${bookList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${bookList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("              <tr>\n");
            out.write("                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.bookId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                <td style=\"text-align:left;padding-left:20px;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.publisher}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                <td>\n");
            out.write("                  ");
            if (_jspx_meth_c_005fchoose_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("                </td>\n");
            out.write("                ");
            if (_jspx_meth_c_005fif_005f6(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("              </tr>\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f2_reused = false;
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                    ");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("                    ");
          if (_jspx_meth_c_005fotherwise_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      _jspx_th_c_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /WEB-INF/jsp/book/bookList.jsp(226,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.status == 'Y'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<span class=\"badge badge-available\">대출가능</span>");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f2 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f2_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      int _jspx_eval_c_005fotherwise_005f2 = _jspx_th_c_005fotherwise_005f2.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<span class=\"badge badge-loaned\">대출중</span>");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f2);
      _jspx_th_c_005fotherwise_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/jsp/book/bookList.jsp(230,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVO.role == 'ADMIN'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                  <td>\n");
          out.write("                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/book/bookModifyView.do?bookId=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.bookId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"btn-edit\">수정</a>\n");
          out.write("                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/book/bookDelete.do?bookId=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.bookId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"btn-delete\" onclick=\"return confirm('삭제하시겠습니까?')\">삭제</a>\n");
          out.write("                  </td>\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f3 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f3_reused = false;
    try {
      _jspx_th_c_005fchoose_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f3.setParent(null);
      int _jspx_eval_c_005fchoose_005f3 = _jspx_th_c_005fchoose_005f3.doStartTag();
      if (_jspx_eval_c_005fchoose_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("      ");
          if (_jspx_meth_c_005fwhen_005f3(_jspx_th_c_005fchoose_005f3, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("      ");
          if (_jspx_meth_c_005fotherwise_005f3(_jspx_th_c_005fchoose_005f3, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f3);
      _jspx_th_c_005fchoose_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f3 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f3_reused = false;
    try {
      _jspx_th_c_005fwhen_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f3);
      // /WEB-INF/jsp/book/bookList.jsp(252,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginVO}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f3 = _jspx_th_c_005fwhen_005f3.doStartTag();
      if (_jspx_eval_c_005fwhen_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        <p class=\"modal-subtitle\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVO.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 — 도서를 검색하고 클릭해서 선택하세요. 여러 권도 가능합니다.</p>\n");
          out.write("\n");
          out.write("        <div class=\"sec-title\">도서 검색</div>\n");
          out.write("        <div class=\"modal-search-row\">\n");
          out.write("          <select id=\"bookSearchType\">\n");
          out.write("            <option value=\"title\">제목</option>\n");
          out.write("            <option value=\"author\">저자</option>\n");
          out.write("            <option value=\"publisher\">출판사</option>\n");
          out.write("          </select>\n");
          out.write("          <input type=\"text\" id=\"bookKeyword\" placeholder=\"예) 노인과 바다\" onkeydown=\"if(event.key==='Enter') searchBook()\">\n");
          out.write("          <button class=\"btn-ms\" onclick=\"searchBook()\">검색</button>\n");
          out.write("        </div>\n");
          out.write("        <div class=\"result-box\" id=\"bookResultBox\"><span>검색 결과가 여기에 표시됩니다.</span></div>\n");
          out.write("        <p class=\"hint\">클릭하면 선택(✔), 다시 클릭하면 해제. 검색어가 바뀌어도 선택된 도서는 유지됩니다.</p>\n");
          out.write("\n");
          out.write("        <div class=\"cart-area\" id=\"cartArea\" style=\"display:none;\">\n");
          out.write("          <div class=\"cart-title\">\n");
          out.write("            선택된 도서 <span id=\"cartCount\">0</span>권\n");
          out.write("            <span onclick=\"clearCart()\">전체 해제</span>\n");
          out.write("          </div>\n");
          out.write("          <div id=\"cartList\"></div>\n");
          out.write("        </div>\n");
          out.write("\n");
          out.write("        <form id=\"loanForm\" action=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/loan/loanApplyMulti.do\" method=\"post\">\n");
          out.write("          <input type=\"hidden\" name=\"memberId\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginVO.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\n");
          out.write("          <div id=\"cartHiddens\"></div>\n");
          out.write("          <button type=\"button\" class=\"btn-submit-loan\" id=\"loanSubmitBtn\" disabled onclick=\"submitLoan()\">\n");
          out.write("            대출 신청하기 (<span id=\"btnCount\">0</span>권)\n");
          out.write("          </button>\n");
          out.write("        </form>\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
      _jspx_th_c_005fwhen_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f3 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f3_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f3);
      int _jspx_eval_c_005fotherwise_005f3 = _jspx_th_c_005fotherwise_005f3.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("        <p class=\"modal-subtitle\">대출할 도서를 먼저 검색해보세요.</p>\n");
          out.write("        <div class=\"sec-title\">도서 검색</div>\n");
          out.write("        <div class=\"modal-search-row\">\n");
          out.write("          <select id=\"bookSearchType\">\n");
          out.write("            <option value=\"title\">제목</option>\n");
          out.write("            <option value=\"author\">저자</option>\n");
          out.write("            <option value=\"publisher\">출판사</option>\n");
          out.write("          </select>\n");
          out.write("          <input type=\"text\" id=\"bookKeyword\" placeholder=\"예) 노인과 바다\" onkeydown=\"if(event.key==='Enter') searchBook()\">\n");
          out.write("          <button class=\"btn-ms\" onclick=\"searchBook()\">검색</button>\n");
          out.write("        </div>\n");
          out.write("        <div class=\"result-box\" id=\"bookResultBox\"><span>검색 결과가 여기에 표시됩니다.</span></div>\n");
          out.write("        <hr class=\"modal-divider\">\n");
          out.write("        <div class=\"login-required-box\">\n");
          out.write("          <div class=\"lrb-title\">대출 신청은 로그인이 필요합니다</div>\n");
          out.write("          <div class=\"lrb-sub\">원하는 도서를 찾으셨나요? 로그인 후 바로 대출할 수 있습니다.</div>\n");
          out.write("          <div class=\"lrb-btn-row\">\n");
          out.write("            <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/user/loginView.do?returnUrl=/book/bookList.do\" class=\"btn-go-login\">로그인 하기</a>\n");
          out.write("            <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/user/joinView.do?returnUrl=/book/bookList.do\" class=\"btn-go-join\">회원가입 하기</a>\n");
          out.write("          </div>\n");
          out.write("        </div>\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f3);
      _jspx_th_c_005fotherwise_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f3_reused);
    }
    return false;
  }
}
