/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2026-05-27 12:35:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원가입 - 폴리 인공지능 도서관</title>\n");
      out.write("<style>\n");
      out.write("  * { margin: 0; padding: 0; box-sizing: border-box; }\n");
      out.write("  body { font-family: 'Georgia', serif; background-color: #F5F0E8; display: flex; flex-direction: column; min-height: 100vh; }\n");
      out.write("  .header { background-color: #5C3D2E; padding: 20px; box-shadow: 0 2px 8px rgba(0,0,0,0.3); text-align: center; position: relative; }\n");
      out.write("  .header h1 { color: #F5E6C8; font-size: 22px; letter-spacing: 1px; }\n");
      out.write("  .header h1 a { color: inherit; text-decoration: none; }\n");
      out.write("  .btn-back { position: absolute; left: 24px; top: 50%; transform: translateY(-50%); color: #C4A882; text-decoration: none; font-size: 13px; border: 1px solid #8A6040; border-radius: 5px; padding: 6px 14px; }\n");
      out.write("  .btn-back:hover { color: #F5E6C8; border-color: #C4A882; }\n");
      out.write("  .join-container { flex: 1; display: flex; align-items: center; justify-content: center; padding: 30px 20px; }\n");
      out.write("  .join-card { background: #FFFDF8; width: 100%; max-width: 460px; padding: 40px; border-radius: 12px; box-shadow: 0 4px 20px rgba(92,61,46,0.15); border: 1px solid #EDE0CE; }\n");
      out.write("  .join-card h2 { color: #5C3D2E; text-align: center; margin-bottom: 28px; font-size: 22px; border-bottom: 2px solid #A0522D; padding-bottom: 10px; }\n");
      out.write("  .input-group { margin-bottom: 18px; }\n");
      out.write("  .input-group label { display: block; margin-bottom: 6px; color: #5C3D2E; font-size: 14px; font-weight: bold; }\n");
      out.write("  .input-row { display: flex; gap: 8px; }\n");
      out.write("  .input-row input { flex: 1; }\n");
      out.write("  .input-group input { width: 100%; padding: 11px 14px; border: 1.5px solid #D4B896; border-radius: 6px; background: #FFF8F0; font-family: inherit; font-size: 14px; }\n");
      out.write("  .input-group input:focus { outline: none; border-color: #A0522D; }\n");
      out.write("  .input-group input.ok  { border-color: #2E7D32; background: #F0FFF0; }\n");
      out.write("  .input-group input.err { border-color: #C62828; background: #FFF0F0; }\n");
      out.write("  .btn-check { background: #5C3D2E; color: #FFF8F0; border: none; border-radius: 6px; padding: 11px 16px; cursor: pointer; font-size: 13px; white-space: nowrap; font-family: inherit; flex-shrink: 0; }\n");
      out.write("  .btn-check:hover { background: #3D2719; }\n");
      out.write("  .btn-check:disabled { background: #A8BFBA; cursor: not-allowed; }\n");
      out.write("  .check-msg { font-size: 12px; margin-top: 5px; min-height: 16px; }\n");
      out.write("  .check-msg.ok  { color: #2E7D32; }\n");
      out.write("  .check-msg.err { color: #C62828; }\n");
      out.write("  .input-hint { font-size: 12px; color: #A08060; margin-top: 4px; }\n");
      out.write("  .btn-join { width: 100%; background: #5C3D2E; color: #F5E6C8; padding: 14px; border: none; border-radius: 6px; cursor: pointer; font-size: 16px; font-weight: bold; margin-top: 8px; font-family: inherit; }\n");
      out.write("  .btn-join:hover { background: #3D2719; }\n");
      out.write("  .btn-join:disabled { background: #A8BFBA; cursor: not-allowed; }\n");
      out.write("  .divider { border: none; border-top: 1px solid #EDE0CE; margin: 16px 0; }\n");
      out.write("  .join-footer { text-align: center; font-size: 14px; color: #A08060; margin-top: 12px; }\n");
      out.write("  .join-footer a { color: #A0522D; text-decoration: none; font-weight: bold; }\n");
      out.write("  .footer { text-align: center; padding: 24px; color: #A08060; font-size: 13px; border-top: 1px solid #DDD0BC; }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"header\">\n");
      out.write("  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/book/bookList.do\" class=\"btn-back\">← 메인으로</a>\n");
      out.write("  <h1><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/book/bookList.do\">📚 폴리 인공지능 도서관</a></h1>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"join-container\">\n");
      out.write("  <div class=\"join-card\">\n");
      out.write("    <h2>📝 회원가입</h2>\n");
      out.write("    <form id=\"joinForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/insertUser.do\" method=\"post\" onsubmit=\"return validateForm()\">\n");
      out.write("      <input type=\"hidden\" name=\"returnUrl\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${returnUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("\n");
      out.write("      <!-- 아이디 + 중복체크 -->\n");
      out.write("      <div class=\"input-group\">\n");
      out.write("        <label>아이디 <span style=\"color:#C62828;\">*</span></label>\n");
      out.write("        <div class=\"input-row\">\n");
      out.write("          <input type=\"text\" id=\"memberId\" name=\"memberId\" placeholder=\"아이디를 입력하세요\" required oninput=\"resetIdCheck()\">\n");
      out.write("          <button type=\"button\" class=\"btn-check\" id=\"btnCheckId\" onclick=\"checkId()\">중복 확인</button>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"check-msg\" id=\"idMsg\"></div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- 비밀번호 -->\n");
      out.write("      <div class=\"input-group\">\n");
      out.write("        <label>비밀번호 <span style=\"color:#C62828;\">*</span></label>\n");
      out.write("        <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"비밀번호를 입력하세요\" required oninput=\"checkPwMatch()\">\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- 비밀번호 확인 -->\n");
      out.write("      <div class=\"input-group\">\n");
      out.write("        <label>비밀번호 확인 <span style=\"color:#C62828;\">*</span></label>\n");
      out.write("        <input type=\"password\" id=\"passwordConfirm\" placeholder=\"비밀번호를 다시 입력하세요\" required oninput=\"checkPwMatch()\">\n");
      out.write("        <div class=\"check-msg\" id=\"pwMsg\"></div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- 이름 -->\n");
      out.write("      <div class=\"input-group\">\n");
      out.write("        <label>이름 <span style=\"color:#C62828;\">*</span></label>\n");
      out.write("        <input type=\"text\" name=\"name\" placeholder=\"이름을 입력하세요\" required>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- 전화번호 -->\n");
      out.write("      <div class=\"input-group\">\n");
      out.write("        <label>전화번호</label>\n");
      out.write("        <input type=\"text\" name=\"phone\" placeholder=\"예) 010-1234-5678\">\n");
      out.write("        <p class=\"input-hint\">※ 도서 대출 시 회원 검색에 사용됩니다.</p>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <button type=\"submit\" class=\"btn-join\" id=\"btnJoin\">가입하기</button>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <hr class=\"divider\">\n");
      out.write("    <div class=\"join-footer\">\n");
      out.write("      이미 회원이신가요? <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/loginView.do?returnUrl=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${returnUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">로그인 하기</a>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"join-footer\" style=\"margin-top:8px;\">\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/book/bookList.do\">← 메인 화면으로 돌아가기</a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"footer\">© 2026 폴리 인공지능 도서관 · Poly AI Library</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("var CP = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("var idChecked = false;   // 중복체크 통과 여부\n");
      out.write("var pwMatched = false;   // 비밀번호 일치 여부\n");
      out.write("\n");
      out.write("/* ── 아이디 중복 체크 ── */\n");
      out.write("function checkId() {\n");
      out.write("  var id = document.getElementById('memberId').value.trim();\n");
      out.write("  var msg = document.getElementById('idMsg');\n");
      out.write("  var inp = document.getElementById('memberId');\n");
      out.write("  if (!id) { msg.textContent = '아이디를 입력해주세요.'; msg.className = 'check-msg err'; return; }\n");
      out.write("\n");
      out.write("  var xhr = new XMLHttpRequest();\n");
      out.write("  xhr.open('GET', CP + '/user/checkId.do?memberId=' + encodeURIComponent(id), true);\n");
      out.write("  xhr.onload = function() {\n");
      out.write("    if (xhr.responseText === 'AVAILABLE') {\n");
      out.write("      msg.textContent = '✔ 사용 가능한 아이디입니다.';\n");
      out.write("      msg.className = 'check-msg ok';\n");
      out.write("      inp.classList.add('ok'); inp.classList.remove('err');\n");
      out.write("      idChecked = true;\n");
      out.write("    } else {\n");
      out.write("      msg.textContent = '✗ 이미 사용 중인 아이디입니다.';\n");
      out.write("      msg.className = 'check-msg err';\n");
      out.write("      inp.classList.add('err'); inp.classList.remove('ok');\n");
      out.write("      idChecked = false;\n");
      out.write("    }\n");
      out.write("  };\n");
      out.write("  xhr.send();\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 아이디 수정 시 체크 초기화 */\n");
      out.write("function resetIdCheck() {\n");
      out.write("  idChecked = false;\n");
      out.write("  var msg = document.getElementById('idMsg');\n");
      out.write("  var inp = document.getElementById('memberId');\n");
      out.write("  msg.textContent = ''; msg.className = 'check-msg';\n");
      out.write("  inp.classList.remove('ok', 'err');\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 비밀번호 일치 확인 ── */\n");
      out.write("function checkPwMatch() {\n");
      out.write("  var pw  = document.getElementById('password').value;\n");
      out.write("  var pw2 = document.getElementById('passwordConfirm').value;\n");
      out.write("  var msg = document.getElementById('pwMsg');\n");
      out.write("  var inp = document.getElementById('passwordConfirm');\n");
      out.write("  if (!pw2) { msg.textContent = ''; pwMatched = false; return; }\n");
      out.write("  if (pw === pw2) {\n");
      out.write("    msg.textContent = '✔ 비밀번호가 일치합니다.';\n");
      out.write("    msg.className = 'check-msg ok';\n");
      out.write("    inp.classList.add('ok'); inp.classList.remove('err');\n");
      out.write("    pwMatched = true;\n");
      out.write("  } else {\n");
      out.write("    msg.textContent = '✗ 비밀번호가 일치하지 않습니다.';\n");
      out.write("    msg.className = 'check-msg err';\n");
      out.write("    inp.classList.add('err'); inp.classList.remove('ok');\n");
      out.write("    pwMatched = false;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 최종 유효성 검사 ── */\n");
      out.write("function validateForm() {\n");
      out.write("  if (!idChecked) {\n");
      out.write("    alert('아이디 중복 확인을 해주세요.');\n");
      out.write("    return false;\n");
      out.write("  }\n");
      out.write("  if (!pwMatched) {\n");
      out.write("    alert('비밀번호가 일치하지 않습니다.');\n");
      out.write("    return false;\n");
      out.write("  }\n");
      out.write("  return true;\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
